"""504 Numerai Crypto Live Universe symbols"""

SYMBOLS_504 = [
    'BTC', 'ETH', 'XRP', 'SOL', 'ADA', 'DOGE', 'MATIC', 'LINK', 'UNI', 'AVAX', 
    'NMR', 'BNB', 'TRX', 'BCH', 'HYPE', 'XMR', 'LEO', 'ZEC', 'XLM', 'LTC', 
    'SUI', 'SHIB', 'WLFI', 'TON', 'CRO', 'MNT', 'DOT', 'BGB', 'AAVE', 'TAO', 
    'OKB', 'NEAR', 'ETC', 'PEPE', 'ICP', 'ENA', 'SKY', 'KCS', 'APT', 'KAS', 
    'POL', 'ALGO', 'ATOM', 'XDC', 'VET', 'FLR', 'FIL', 'QNT', 'GT', 'BDX', 
    'SEI', 'BONK', 'JUP', 'CAKE', 'NEXO', 'CRV', 'FTN', 'XTZ', 'DASH', 'FET', 
    'IMX', 'MERL', 'SPX', 'ETHFI', 'VIRTUAL', 'STX', 'MORPHO', 'AERO', 'TEL', 'AB', 
    'STRK', 'TIA', 'SYRUP', 'GRT', 'BTT', 'JST', 'CFX', 'CHZ', 'BSV', 'SUN', 
    'TWT', 'IOTA', 'NFT', 'KAIA', 'GNO', 'BAT', 'DCR', 'WIF', 'ZK', 'ZRO', 
    'PENDLE', 'FARTCOIN', 'JASMY', 'FLOW', 'HNT', 'COMP', 'THETA', 'ZBCN', 'MON', 'DEXE', 
    'NEO', 'RAY', 'APEPE', 'AR', 'LUNC', 'QRL', 'WFI', 'XEC', '1INCH', 'TRAC', 
    'GLM', 'FLUID', 'ULTIMA', 'RUNE', 'EIGEN', 'MX', 'CVX', 'KMNO', 'W', 'EGLD', 
    'UDS', 'CHEEMS', 'WEMIX', 'XCN', 'PROM', 'DEEP', 'SFP', 'FTT', 'APE', 'SNX', 
    'RSR', 'ATH', 'AMP', 'BRETT', 'GOMINING', 'ZEN', 'DYDX', 'BEAM', 'SUPER', 'ZANO', 
    'FORM', 'BMX', 'QTUM', 'TOSHI', 'TFUEL', 'CTC', 'KSM', 'GAS', 'VELO', 'COW', 
    'YFI', 'TURBO', 'CORE', 'AIOZ', 'FLZ', 'CKB', 'RVN', 'LINEA', 'DGB', 'AWE', 
    'ALEO', 'BURN', 'AKT', 'DHN', 'SHFL', 'ZRX', 'MINA', 'BabyDoge', 'MOVE', 'DOG', 
    'T', 'RON', 'SAFE', 'ZIL', 'EDU', 'QUBIC', 'GMX', 'ORDI', 'HSK', 'HOT', 
    'MOG', 'OM', 'REQ', 'ASTR', 'KAVA', 'SUSHI', 'SC', 'WAVES', 'MOCA', 'ROSE', 
    'ME', 'ZIG', 'DRIFT', 'BAN', 'XVG', 'AXL', 'XPR', 'ACH', 'VTHO', 'BLUR', 
    'LRC', 'LUNA', 'XYO', 'GRASS', 'NPC', 'VR', 'MOODENG', 'XVS', 'EUL', 'SNEK', 
    'IOTX', 'RED', 'ELF', 'CELO', 'ORCA', 'SNT', 'XCH', 'CFG', 'UMA', 'CSPR', 
    'FRAX', 'QAI', 'SKL', 'AIC', 'ALT', 'MEME', 'APEX', 'PUNDIX', 'OMI', 'SQD', 
    'ICX', 'ETHW', 'SSV', 'ARDR', 'MASK', 'RLC', 'TRB', 'COTI', 'SRX', 'BAND', 
    'LBT', 'ONE', 'SOLO', 'NOT', 'PEAQ', 'OG', 'ENJ', 'BB', 'POLYX', 'WOO', 
    'BABY', 'ONT', 'STORJ', 'ARK', 'IOST', 'LISTA', 'LSK', 'BNT', 'HIVE', 'YGG', 
    'POWR', 'GMT', 'SMART', 'G', 'KNC', 'ORBS', 'METIS', 'BICO', 'HONEY', 'CTK', 
    'SPELL', 'VENOM', 'SXP', 'FIDA', 'CYBER', 'FLUX', 'SWFTC', 'BAL', 'CVC', 'USUAL', 
    'BIGTIME', 'API3', 'SHX', 'CARV', 'ACT', 'AUDIO', 'WMTX', 'ILV', 'OSMO', 'LAVA', 
    'TNSR', 'FB', 'IO', 'USTC', 'BLAST', 'IQ', 'BITCOIN', 'LQTY', 'BANANAS31', 'ONG', 
    'GIGA', 'ZENT', 'WAXP', 'DAG', 'TAIKO', 'STEEM', 'ACX', 'AEVO', 'ORDER', 'CHR', 
    'SCRT', 'MANTA', 'CPOOL', 'PRO', 'CBK', 'NYM', 'POND', 'DIA', 'RIF', 'AUCTION', 
    'PRIME', 'SATS', 'AIXBT', 'GNS', 'DBR', 'GEMS', 'MAGIC', 'MTL', 'CLANKER', 'DYM', 
    'BFC', 'CHEEL', 'XAI', 'AERGO', 'CTSI', 'CHEX', 'WIN', 'MPLX', 'BANANA', 'CELR', 
    'ORE', 'PHA', 'GAME', 'QKC', 'DKA', 'ELON', 'ADS', 'ZEREBRO', 'POKT', 'ALI', 
    'AURA', 'MOVR', 'MED', 'GRND', 'PIXEL', 'RAIL', 'COOKIE', 'SOPH', 'MAPO', 'CGPT', 
    'ELA', 'LAB', 'THE', 'REZ', 'JOE', 'DEGEN', 'GLMR', 'WCT', 'OXT', 'CATI', 
    'IAG', 'A8', 'SANTOS', 'ACE', 'RIO', 'FORTH', 'C98', 'AGLD', 'DEVVE', 'ANYONE', 
    'DUSK', 'SOLV', 'MBL', 'DOGS', 'STO', 'AGI', 'MAV', 'BIFI', 'PYR', 'BOBA', 
    'DENT', 'SUPRA', 'CAT', 'ROAM', 'AVA', 'BERT', 'PUFFER', 'ELIZAOS', 'SAGA', 'FAI', 
    'MMUI', 'OGN', 'ALCX', 'ARPA', 'HFT', 'VRA', 'FUN', 'ZKJ', 'RARE', 'AI', 
    'TAI', 'AITECH', 'RSC', 'ALICE', 'PORTAL', 'CHILLGUY', 'LUMIA', 'HIGH', 'VANRY', 'ATA', 
    'AVAIL', 'PONKE', 'ADX', 'XPLA', 'RAD', 'TRU', 'PHB', 'NTRN', 'MIN', 'NAVX', 
    'ASD', 'MBOX', 'AQT', 'LAT', 'MLN', 'NEON', 'GRS', 'SYS', 'WAN', 'HMSTR', 
    'ATS', 'DODO', 'SCR', 'PORTO', 'ACS', 'FCT', 'DSYNC', 'LMWR', 'LAZIO', 'ASR', 
    'OL', 'COQ', 'TLM', 'APU', 'PAAL', 'LYX', 'FORT', 'L3', 'FARM', 'NFP', 
    'GTC', 'RDNT', 'WIBE', 'PIVX', 'OAS', 'AMO', 'MAVIA', 'ALPINE', 'DAO', 'BAR', 
    'PSG', 'OMG', 'ACA', 'XEM', 'DF', 'BADGER', 'D', 'VIC', 'CXT', 'JUV', 
    'A2Z', 'HIPPO', 'HOOK', 'BRISE', 'NIBI', 'DEGO', '$PURPE', 'BEL', 'SWEAT', 'FIO', 
    'MAJOR', 'BLUE', 'IDEX', 'SKI', 'AL', 'RSS3', 'GHST', 'WOD', 'NKN', 'MDT', 
    'SYN', 'ALEPH', 'PRCL', 'BTR',
]
# Total: 504 symbols
assert len(SYMBOLS_504) == 504
